### ISSUE TITLE
Failed to load kernel extension "RazorKernelExtension"

### ISSUE THREAD

**Issue by GeorgeS2019** [plbonneville/RazorInteractive#149]
What could cause this?

 Failed to load kernel extension "RazorKernelExtension" from assembly` user\.nuget\packages\razorinteractive\1.0.7\interactive-extensions\dotnet\RazorInteractive.dll`

**Comment by GeorgeS2019** [comment]
Even after managed to install, I still get error
![image ](https://user-images.githubusercontent.com/49812372/188283180-095168d7-c42a-4c49-9358-faa14548e3a9.png)

```
Error: Required command was not provided.
Unrecognized command or argument '#!razor'.
```

**Comment by GeorgeS2019** [comment]
solved

**Comment by ekennedy6334** [comment]
How??
